// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYcvu087L49DzI3nDhKVl57ddnbKKmb4w',
    appId: '1:1087381563192:web:d1a5ea9c5fdc0c64e043cd',
    messagingSenderId: '1087381563192',
    projectId: 'termproject24',
    authDomain: 'termproject24.firebaseapp.com',
    storageBucket: 'termproject24.appspot.com',
    measurementId: 'G-YXECZLQKNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBie5_o-S2yBg_ie2Vw0GS7HfHpGZ221TY',
    appId: '1:1087381563192:android:c059fa7d3bca872fe043cd',
    messagingSenderId: '1087381563192',
    projectId: 'termproject24',
    storageBucket: 'termproject24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrLosDuf6imxDmnBecbKvOkDRom01xBZo',
    appId: '1:1087381563192:ios:53d6e48355fcdf10e043cd',
    messagingSenderId: '1087381563192',
    projectId: 'termproject24',
    storageBucket: 'termproject24.appspot.com',
    iosBundleId: 'com.example.devhiveFriendSanchez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrLosDuf6imxDmnBecbKvOkDRom01xBZo',
    appId: '1:1087381563192:ios:9bd3a27ec7e9a9ece043cd',
    messagingSenderId: '1087381563192',
    projectId: 'termproject24',
    storageBucket: 'termproject24.appspot.com',
    iosBundleId: 'com.example.devhiveFriendSanchez.RunnerTests',
  );
}
